### ISSUE TITLE
Unnecessary `unsafe` in `gpio::v2` refactor

### ISSUE THREAD

**Issue by bradleyharden** [robamu-org/va108xx-hal-rs#11]
FYI, the code [here](https://github.com/robamu-org/va108xx-hal-rs/blob/454a44826d30dc61b4fa5b323e8c776e7f50cb60/src/gpio_v2/pins.rs#L228-L242) does not need the `unsafe` transmute. That was necessary for compatibility between our (`atsamd-hal`) `gpio::v1` and `gpio::v2` modules, but you can just return `self` in both instances.

Edit: I should clarify. As written, you need the transmute. But you can change the trait implementation to:

```rust
impl<I: PinId, M: PinMode> AsRef<Self> for Pin<I, M> {
    #[inline]
    fn as_ref(&self) -> &Self {
        self
    }
}
```

We needed the implementation to be generic over all `P: AnyPin`, but that's not necessary in most normal cases.

**Comment by robamu** [comment]
Thanks, I changed the trait implementation
